### ISSUE TITLE
Add Ethernet Support

### ISSUE THREAD

**Issue by sdrabb** [jenschr/Teensy-4.1-example#2]
can we collaborate to start integrating some peripheral to the board? why not eth for example?
Thanks @jenschr

**Comment by jenschr** [comment]
@sdrabb Hi. This board isn't really meant to be used as is. It's more like a starting point for others. Adding Ethernet is not hard though. Just follow the schematic and add a similar ETH plug as PJRC is using? https://www.pjrc.com/store/j1b1211ccd.pdf Then you lay that out in a board that is better suited for your purpose?

**Comment by sdrabb** [comment]
great, thanks!
