### ISSUE TITLE
D41

### ISSUE THREAD

**Issue by Fluxanode** [jenschr/Teensy-4.1-example#3]
You say D41 was not brought out.  What is D41, I can't find that pin anyway?

**Comment by jenschr** [comment]
D41 refers to the Teensy pin marked as just 41 in the official pinout https://www.pjrc.com/teensy/pinout.html

**Comment by Fluxanode** [comment]
Thanks.  Why did you leave it out of your design?

**Comment by jenschr** [comment]
Lack of space 😉
